### ISSUE TITLE
[Bug] Crash after attempt to play video

### ISSUE THREAD

**Issue by vasyl91** [YTVanced/Vanced#399]
**Bug description**
After updating Magisk, Youtube crashes right after I try to open video or few seconds after sliding down/switching tabs.

```
time: 1611909819469
msg: java.lang.IllegalArgumentException: Remote stack trace:
	at com.android.server.media.MediaSessionService.enforcePackageName(MediaSessionService.java:490)
	at com.android.server.media.MediaSessionService.access$2100(MediaSessionService.java:104)
	at com.android.server.media.MediaSessionService$SessionManagerImpl.createSession(MediaSessionService.java:1012)
	at android.media.session.ISessionManager$Stub.onTransact(ISessionManager.java:239)
	at android.os.Binder.execTransactInternal(Binder.java:1021)

stacktrace: java.lang.IllegalArgumentException: packageName is not owned by the calling process
	at android.os.Parcel.createException(Parcel.java:2075)
	at android.os.Parcel.readException(Parcel.java:2039)
	at android.os.Parcel.readException(Parcel.java:1987)
	at android.media.session.ISessionManager$Stub$Proxy.createSession(ISessionManager.java:558)
	at android.media.session.MediaSessionManager.createSession(MediaSessionManager.java:114)
	at android.media.session.MediaSession.<init>(MediaSession.java:194)
	at kj.<init>(PG:8)
	at aoxs.get(Unknown Source:1)
	at aoxu.g(PG:1)
	at aoxu.f(PG:2)
	at amkw.b(PG:1)
	at dnk.f(PG:32)
	at dnk.get(PG:276)
	at poe.kj(PG:3)
	at acea.a(PG:4)
	at acds.run(PG:19)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:915)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.media.MediaSessionService.enforcePackageName(MediaSessionService.java:490)
	at com.android.server.media.MediaSessionService.access$2100(MediaSessionService.java:104)
	at com.android.server.media.MediaSessionService$SessionManagerImpl.createSession(MediaSessionService.java:1012)
	at android.media.session.ISessionManager$Stub.onTransact(ISessionManager.java:239)
	at android.os.Binder.execTransactInternal(Binder.java:1021)
```

**Variant**
Root

**Vanced version**
16.02.35 - Build - 01.47.00

**Android version**
Android 10.0

**Device**
Redmi Note 8T

**Comment by H4XKER** [comment]
Yeah it happen to me to on android 5.0 Sony C3 D2553 it just crash after opening i tried playing video. Even after switching to exoplayer v2 still same
