### ISSUE TITLE
[Bug] Crashing after reboot the phone

### ISSUE THREAD

**Issue by marcussacana** [YTVanced/Vanced#956]
**Bug description**
After install the YouTube vanced he works, but that's only while I don't Reboot the phone, then he crash while I don't reinstall the vanced

**Variant**
Root

**Vanced version**
Tested with many versions, same issue, but my current is the 16.14.34

**Android version**
Android 10, MIUI 12.0.1

**Device**
Redmi Note 9S

**Steps to Reproduce**
Steps to reproduce the error:
1. Install
2. Reboot

**Log:**
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.google.android.youtube/com.google.android.apps.youtube.app.watchwhile.WatchWhileActivity}: android.view.InflateException: Binary XML file line #25 in com.google.android.youtube:layout/watch_while_activity_with_slim_status_bar: Binary XML file line #19 in com.google.android.youtube:layout/single_next_gen_watch_layout: Error inflating class com.google.android.apps.youtube.app.watch.nextgenwatch.ui.NextGenWatchLayout
	at android.app.ActivityThread.performLaunchActivity(Unknown Source:621)
	at android.app.ActivityThread.handleLaunchActivity(Unknown Source:47)
	at android.app.servertransaction.LaunchActivityItem.execute(Unknown Source:63)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(Unknown Source:77)
	at android.app.servertransaction.TransactionExecutor.execute(Unknown Source:73)
	at android.app.ActivityThread$H.handleMessage(Unknown Source:43)
	at android.os.Handler.dispatchMessage(Unknown Source:19)
	at android.os.Looper.loop(Unknown Source:242)
	at android.app.ActivityThread.main(Unknown Source:98)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
	at com.android.internal.os.ZygoteInit.main(Unknown Source:275)
Caused by: android.view.InflateException: Binary XML file line #25 in com.google.android.youtube:layout/watch_while_activity_with_slim_status_bar: Binary XML file line #19 in com.google.android.youtube:layout/single_next_gen_watch_layout: Error inflating class com.google.android.apps.youtube.app.watch.nextgenwatch.ui.NextGenWatchLayout
Caused by: android.view.InflateException: Binary XML file line #19 in com.google.android.youtube:layout/single_next_gen_watch_layout: Error inflating class com.google.android.apps.youtube.app.watch.nextgenwatch.ui.NextGenWatchLayout
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at android.view.LayoutInflater.createView(Unknown Source:210)
	at android.view.LayoutInflater.createViewFromTag(Unknown Source:71)
	at android.view.LayoutInflater.createViewFromTag(Unknown Source:6)
	at android.view.LayoutInflater.rInflate(Unknown Source:92)
	at android.view.LayoutInflater.rInflateChildren(Unknown Source:9)
	at android.view.LayoutInflater.parseInclude(Unknown Source:292)
	at android.view.LayoutInflater.rInflate(Unknown Source:71)
	at android.view.LayoutInflater.rInflateChildren(Unknown Source:9)
	at android.view.LayoutInflater.parseInclude(Unknown Source:292)
	at android.view.LayoutInflater.rInflate(Unknown Source:71)
	at android.view.LayoutInflater.rInflateChildren(Unknown Source:9)
	at android.view.LayoutInflater.rInflate(Unknown Source:103)
	at android.view.LayoutInflater.rInflateChildren(Unknown Source:9)
	at android.view.LayoutInflater.inflate(Unknown Source:107)
	at android.view.LayoutInflater.inflate(Unknown Source:27)
	at android.view.LayoutInflater.inflate(Unknown Source:5)
	at dha.aw(PG:6)
	at dgn.get(PG:107)
	at dgo.a(PG:1)
	at dgo.h(PG:2)
	at dha.ht(PG:1)
	at dgt.d(PG:76)
	at dgt.get(PG:196)
	at awil.get(PG:1)
	at nat.<init>(PG:15)
	at dha.ln(PG:10)
	at dha.pi(PG:16)
	at mxn.c(PG:1)
	at dvx.onCreate(PG:1)
	at nah.onCreate(PG:1)
	at com.google.android.apps.youtube.app.watchwhile.WatchWhileActivity.onCreate(PG:40)
	at android.app.Activity.performCreate(Unknown Source:19)
	at android.app.Activity.performCreate(Unknown Source:1)
	at android.app.Instrumentation.callActivityOnCreate(Unknown Source:3)
	at android.app.ActivityThread.performLaunchActivity(Unknown Source:376)
	at android.app.ActivityThread.handleLaunchActivity(Unknown Source:47)
	at android.app.servertransaction.LaunchActivityItem.execute(Unknown Source:63)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(Unknown Source:77)
	at android.app.servertransaction.TransactionExecutor.execute(Unknown Source:73)
	at android.app.ActivityThread$H.handleMessage(Unknown Source:43)
	at android.os.Handler.dispatchMessage(Unknown Source:19)
	at android.os.Looper.loop(Unknown Source:242)
	at android.app.ActivityThread.main(Unknown Source:98)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
	at com.android.internal.os.ZygoteInit.main(Unknown Source:275)
Caused by: java.lang.ExceptionInInitializerError
	at ssr.<init>(PG:14)
	at ssi.b(PG:1)
	at dha.pf(PG:75)
	at dha.pc(PG:4)
	at dgt.a(PG:139)
	at dgt.get(PG:196)
	at awil.get(PG:1)
	at ixl.<init>(PG:4)
	at dha.aF(PG:4)
	at dha.qS(PG:4)
	at dha.lO(PG:2)
	at dkk.h(PG:6)
	at mqo.e(PG:1)
	at mqo.<init>(PG:4)
	at com.google.android.apps.youtube.app.watch.nextgenwatch.ui.NextGenWatchLayout.<init>(PG:5)
	... 48 more
Caused by: daw: libelements.so
	at day.e(PG:52)
	at day.g(PG:6)
	at dix.a(Unknown Source:2)
	at amyi.f(PG:8)
	at amyi.e(PG:5)
	at amyi.a(PG:1)
	at tgt.A(PG:1)
	at com.youtube.android.libraries.elements.templates.PbToFb.<clinit>(PG:1)
	... 63 more
```
By the way, the same issue happen with the music vanced

**Comment by milindgoel15** [comment]
Please read regarding "**uninstall on reboot**" from [vanced guides](https://play.google.com/store/apps/details?id=com.vanced.faq) beforehand.
